version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./docker/Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  datascience:
    build: ./docker/Dockerfile.datascience
    depends_on:
      - backend